use_frameworks!

platform :ios, '8.0'

target 'XKNotificationCenter_Example' do
  pod 'XKNotificationCenter', :path => '../'

  target 'XKNotificationCenter_Tests' do
    inherit! :search_paths

    
  end
end
